### ISSUE TITLE
Table header is wrapping the text, but its not the word wrap

### ISSUE THREAD

**Issue by ruhijain** [someatoms/jsPDF-AutoTable#57] opened 2015-07-27 08:59 UTC
In my table in the PDF,  The Table header does wrap the text after version 1.3.2 but still it is not the complete word wrap. I would really appreciate if some assistance can be provided for this at the earliest. 

For example the problem is , If Table column  is "Record No." , Its shows Reco in one line and the rest in other. If "Manufacturer" is the text than it show Manufac in one line, rest in other line.

**Comment by ruhijain** [comment] 2015-07-30 09:03
I managed to do it for now, I do encounter another problem though.

When a particular cell data has long string into it, the row height dynamically increases but it then goes out of the page crossing the footer.

Even when the bottom margin is specified, why this happens? Whats the solution?

**Comment by someatoms** [comment] 2015-08-06 23:45
I think the issue you describe is the same as in #53? If so, it is fixed in v2.0 which I will release the coming week. Sorry for the late reply.

**Comment by ruhijain** [comment] 2015-08-07 04:05
Well, Yes it looks like the same issue. I will wait for v2.0 then. Will it be backward compatible? Just worried if i have to change my code a lot. I have used it the library at many places.

**Comment by someatoms** [comment] 2015-08-07 08:23
There is no big API changes and your code should probably be fine. It will not be 100% backwards campatible unfortunately however. I have added better styling support which meant that I had to make some changes to the renderCell and renderHeaderCell methods.

**Comment by ruhijain** [comment] 2015-08-07 08:41
ohh okay. I guess i would have to change my code then. Anyways will wait for the update, :)

**Comment by ruhijain** [comment] 2015-08-14 07:26
Can you provide a quick fix for this. I really need some urgent fix for this issue. 

Any alternative, if not the upgrade to 2.0?

**Comment by ruhijain** [comment] 2015-08-19 04:38
Trying to find some workaround on this issue. In renderCell i check for autoTableEndPosY and compare it with doc.internal.pageSize.height, if autoTableEndPosY exceeds a specific value i want to change page and move the records from then onwards to new page. I did addPage() , But how do i make it to add next all records to this new page?

**Comment by someatoms** [comment] 2015-08-19 10:06
Unfortunately I can't see a way to do this without modifying the source so that would be your best option for now. If you do fix it, make sure you send a pull request. The 2.0 release got a bit delayed, but hopefully I can release it today.

**Comment by ruhijain** [comment] 2015-08-19 10:46
I fixed it my just doing a small change in jspdf.plugin.autotable.js :)

Btw, just curious to know, Can i put links in PDF file?

**Comment by someatoms** [comment] 2015-08-19 10:57
Sweet! There is an annotations plugin for jspdf that makes it possible to add links. It is included in version 1.1 of jspdf, but I think you can add it to earlier versions as well.

**Comment by ruhijain** [comment] 2015-08-19 10:59
Okay thanks. Will give it a try. Meanwhile, I am not sure on how to send a Pull request. I do not see any option to create one when i go to Pull request option on my Github page

**Comment by someatoms** [comment] 2015-08-21 12:11
Closing as duplicate of #53

**Closed by someatoms** 2015-08-21 12:11 UTC
