### ISSUE TITLE
Sub header colspan

### ISSUE THREAD

**Issue by lobosan** [someatoms/jsPDF-AutoTable#41] opened 2015-06-18 03:57 UTC
Hi, I want to add a sub header to my table but instead of adding a new row, the row where I want to add the sub header it's being replaced. I noticed that in the example is doing the same. Is there any way to add the sub header without replacing any row?

**Comment by someatoms** [comment] 2015-06-18 08:04
Duplicate of issue [#42](https://github.com/someatoms/jsPDF-AutoTable/issues/42)

**Closed by someatoms** 2015-06-18 08:04 UTC
