### ISSUE TITLE
linebreaks not working in metoer project

### ISSUE THREAD

**Issue by jazzdragon** [someatoms/jsPDF-AutoTable#36] opened 2015-06-07 02:21 UTC
Hi,
I like what you did here.
For some reason, no matter what I do, I always get the 'ellipsize' behavior. Also, when I set overflow to false and look at the text passed to renderCell, I get the ellipsized text.

**Comment by jazzdragon** [comment] 2015-06-07 02:23
Is it a version issue? I'm pretty clueless at this point, and would love even a dirty workaround.
Thanks!

**Comment by ankur2728** [comment] 2015-06-08 16:16
I am facing the same issue. Linebreak is not working at all. I am also getting ellipsize behavior always. Please let me know the workaround. Need it urgently

**Comment by someatoms** [comment] 2015-06-09 06:53
After some quick experimentation I realized that there is a bug that makes linebreaks only work when the `overflowColumns` option is set. For now you can simply list all columns you want to overflow there, but I will look into this as soon as possible.

I can't reproduce the other issue it right now. Can you confirm that it is a meteor issue only?

**Comment by ankur2728** [comment] 2015-06-09 07:08
I am trying it in my application. I have set the overflowcolumns to false, Overflow to linebreak, then it is not coming as ellipsize but extra characters are hiding. I will check after setting overflowcolumns.

**Comment by someatoms** [comment] 2015-06-09 07:16
I published a fix now for the linebreak issue. Let me know if it works for you!

**Comment by ankur2728** [comment] 2015-06-09 08:08
This plugin is wonderful. Thanks a ton. From where can i get the updated plugin with your fix.

**Comment by someatoms** [comment] 2015-06-09 08:46
Thanks! You can download it from this github repo or via bower as stated in the the README.

**Comment by someatoms** [comment] 2015-06-14 10:36
Is this issue resolved with the latest update?

**Closed by someatoms** 2015-06-14 10:36 UTC
